In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/PROJECT/AAPL.xlsx")

In [ ]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    datetime64[ns]
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 10.2 KB

In [ ]:
print(len(df.columns))

7

In [ ]:
df.isnull()

      Date   Open   High    Low  Close  Adj Close  Volume
0    False  False  False  False  False      False   False
1    False  False  False  False  False      False   False
2    False  False  False  False  False      False   False
3    False  False  False  False  False      False   False
4    False  False  False  False  False      False   False
..     ...    ...    ...    ...    ...        ...     ...
179  False  False  False  False  False      False   False
180  False  False  False  False  False      False   False
181  False  False  False  False  False      False   False
182  False  False  False  False  False      False   False
183  False  False  False  False  False      False   False

[184 rows x 7 columns]

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
179    False
180    False
181    False
182    False
183    False
Length: 184, dtype: bool

In [ ]:
df['Daily_Delta'] = df['Close'] - df['Open']
display(df.head())

,Date,Open,High,Low,Close,Adj Close,Volume,Daily_Delta
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700,-0.969993
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200,0.780006
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800,-3.660004
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900,6.900001
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600,3.150002